name: Validate with hassfest
permissions:
  contents: read

on:
  # push:
  # pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
        with:
          persist-credentials: false
      - uses: home-assistant/actions/hassfest@master
